title : Environmental systems analysis
author: Max Koslowski
logo: 'IndustrialEcology_logo_tiny.jpg'

# Short description about the book
description: >-
  An overview of the research fields industrial ecology and environmental systems analysis.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/maximikos/indeco
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
