title : Environmental systems analysis
author: Maximilian Koslowski
logo: 'nemora_logo.png'

# Short description about the book
description: >-
  An overview of the research fields industrial ecology and environmental systems analysis.

execute:
  execute_notebooks           : off # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

# HTML-specific settings
html:
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  comments:                         # Add ability for comments via utterances and hypothesis
    utterances:
      repo: "maximikos/indeco"
    hypothesis: true
  extra_footer:
    <p>
    :mountain_snow: :ocean: :evergreen_tree: [Privacy policy](./docs/special/privacy.md)
    </p>

sphinx:
  config:
    html_show_copyright       : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/maximikos/indeco
  path_to_book                : "" # was before: mini_book

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex

# Exclude files
exclude_patterns: [docs/python/*]