title : "" # Environmental systems analysis
author: International Society for Industrial Ecology
copyright: "2023"
logo: 'nemora_logo_small.png'
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

################################################################################
# Short description about the book
description: >-
  An overview of the research fields industrial ecology and environmental systems analysis.

################################################################################
# Adding extra funcctionality on the page
# HTML-specific settings
html:
  favicon                   : "./favicon.ico"
  home_page_in_navbar       : false  # Whether to include your home page in the left Navigation Bar
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in

  use_multitoc_numbering    : false

  extra_navbar              : Visit our <a href="https://github.com/maximikos/indeco">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>  # Will be displayed underneath the left navbar. (Or simply remove this line to display extra_navbar, i.e. put "")

  comments:                         # Add ability for comments via utterances and hypothesis. It seams that the site-wide setting for utterances does not work.
    utterances:
      src: "https://utteranc.es/client.js"
      repo: "maximikos/indeco"
      issue-term: "pathname"
      theme: "github-light"
      crossorigin: "anonymous"
      async: "async"
      label: "💬 comment"
      crossorigin: "anonymous"
    hypothesis: true

  extra_footer:
    <p>
    &#x1F3D4; &#127754; &#x1F332; <a href="./special/privacy.md">Privacy policy</a>
    </p>

only_build_toc_files: false # privacy.md is not part of toc and has to be built as well

################################################################################
# Settings for external services
# Sphinx settings
sphinx:
  config:
    html_show_copyright       : true
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    language                  : en   # include explicitly for accessibility
    today_fmt                 : '%d %b %Y'
    mathjax_path              : https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    suppress_warnings         : ["mystnb.unknown_mime_type"]
    
    


# Binder settings
binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"


################################################################################
# Notebook and repo settings
# Notebooks
execute:
  execute_notebooks           : auto # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off"). Cache avoid re-execution
  timeout                     : 100 # Time each notebook cell is allowed to run, in seconds
  allow_errors                : true
  stderr_output               : show
  nb_execution_show_tb        : true

notebook_interface            : "notebook" # Interact link settings. Or choose "jupyterlab" or "classic"

# Launch button settings
repository:
  url                         : https://github.com/maximikos/indeco
  branch                      : main
  path_to_book                : "" # was before: mini_book

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex


#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist